global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'da-server'
    static_configs:
      - targets: ['da-server:3100']
    metrics_path: '/metrics'
  - job_name: 'op-node'
    static_configs:
      - targets: ['op-node:7300']
